/**
 * Comprehensive IT Job Positions Database
 * Used for CV Job-Specific Suitability Assessment
 */

const IT_JOB_POSITIONS = [
  {
    id: 'software-engineer',
    name: 'Software Engineer / Kỹ sư Phần mềm',
    rating: '9.5/10',
    category: 'Development',
    description: 'Web, Mobile, Enterprise Systems development',
    demandSalary: 'Junior: 10-25tr, Senior: 40-80tr/tháng',
    characteristics: 'Giá trị chuyển từ "code nhanh" sang "tư duy kiến trúc, giải quyết bài toán phức tạp"',
    requiredSkills: ['java/spring boot', 'nodejs/express', 'c#/.net', 'sql/nosql', 'git', 'restful api', 'oop', 'design patterns', 'agile/scrum', 'docker', 'ci/cd basics'],
    bonusSkills: ['kubernetes', 'microservices', 'system design', 'clean architecture', 'aws/gcp/azure', 'message queues (kafka/rabbitmq)'],
    certifications: ['AWS Certified Developer', 'Oracle Certified', 'Microsoft Certified']
  },
  {
    id: 'ai-ml-engineer',
    name: 'AI / Machine Learning Engineer',
    rating: '10/10',
    category: 'AI & Data',
    description: 'LLM, NLP, Computer Vision, Generative AI',
    demandSalary: 'Lương cao hơn 20-30% so với mức trung bình IT',
    characteristics: 'Rất khó học, đòi hỏi nền tảng Toán (Đại số, Xác suất) và Khoa học Máy tính xuất sắc',
    requiredSkills: ['python', 'tensorflow', 'pytorch', 'scikit-learn', 'numpy', 'pandas', 'machine learning', 'deep learning', 'nlp', 'computer vision', 'statistics', 'linear algebra'],
    bonusSkills: ['llm', 'langchain', 'huggingface', 'mlops', 'aws sagemaker', 'model deployment', 'rag'],
    certifications: ['Google ML Engineer', 'AWS ML Specialty', 'TensorFlow Developer Certificate']
  },
  {
    id: 'cloud-devops',
    name: 'Cloud / DevOps / SRE Engineer',
    rating: '9/10',
    category: 'Infrastructure',
    description: 'Quản lý server, CI/CD, đảm bảo hệ thống vận hành ổn định',
    demandSalary: 'Nhu cầu cực kỳ ổn định, lương hấp dẫn do tính phức tạp cao',
    characteristics: 'Thường SE chuyển sang, ít vị trí Junior',
    requiredSkills: ['linux', 'docker', 'kubernetes', 'aws', 'azure', 'gcp', 'terraform', 'ci/cd', 'jenkins', 'gitlab ci', 'monitoring', 'bash'],
    bonusSkills: ['ansible', 'prometheus', 'grafana', 'istio', 'helm', 'argocd', 'infrastructure as code'],
    certifications: ['AWS Solutions Architect', 'CKA', 'Azure Administrator', 'GCP Professional']
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity / An ninh mạng',
    rating: '9.5/10',
    category: 'Security',
    description: 'Penetration testing, bảo mật hệ thống, ứng phó sự cố',
    demandSalary: 'Nhu cầu tăng mạnh hàng năm, thu nhập rất cao và ổn định tuyệt đối',
    characteristics: 'Đòi hỏi học tập liên tục, chứng chỉ chuyên môn, tư duy "đi trước đón đầu"',
    requiredSkills: ['networking', 'linux', 'firewall', 'ids/ips', 'siem', 'penetration testing', 'vulnerability assessment', 'cryptography', 'security audit', 'incident response'],
    bonusSkills: ['reverse engineering', 'malware analysis', 'forensics', 'soc', 'zero trust', 'devsecops'],
    certifications: ['CISSP', 'CEH', 'CompTIA Security+', 'OSCP', 'CISM']
  },
  {
    id: 'data-engineer',
    name: 'Data Engineer / Data Scientist',
    rating: '9/10',
    category: 'AI & Data',
    description: 'Thu thập, lưu trữ, phân tích dữ liệu lớn (Big Data)',
    demandSalary: 'Rất cao trong Fintech, Healthcare, E-commerce',
    characteristics: 'Dễ ứng dụng AI, đòi hỏi logic xử lý và trực quan hóa dữ liệu tốt',
    requiredSkills: ['python', 'sql', 'spark', 'hadoop', 'etl', 'data warehouse', 'airflow', 'kafka', 'data modeling', 'statistics', 'power bi', 'tableau'],
    bonusSkills: ['dbt', 'snowflake', 'databricks', 'data lake', 'real-time streaming', 'feature engineering'],
    certifications: ['Google Data Engineer', 'AWS Data Analytics', 'Databricks Certified']
  },
  {
    id: 'frontend-developer',
    name: 'Front-End Developer / Web Designer',
    rating: '8/10',
    category: 'Development',
    description: 'Xây dựng giao diện người dùng tương tác',
    demandSalary: 'Số lượng ứng viên Junior đông, lương tốt nhưng cạnh tranh cao',
    characteristics: 'AI viết code giao diện rất mạnh, cần tập trung vào UX/UI, performance, accessibility',
    requiredSkills: ['react/vue/angular', 'typescript', 'state management (redux/zustand)', 'tailwind/css modules', 'responsive design', 'git', 'webpack/vite', 'rest/graphql integration'],
    bonusSkills: ['next.js/nuxt', 'ssr/ssg', 'web performance optimization', 'accessibility (a11y)', 'storybook', 'pwa', 'ci/cd for frontend'],
    certifications: ['Meta Front-End Developer', 'Google UX Design', 'AWS Front-End']
  },
  {
    id: 'backend-developer',
    name: 'Back-End Developer / Kỹ sư Backend',
    rating: '9/10',
    category: 'Development',
    description: 'Thiết kế API, cơ sở dữ liệu, xử lý logic nghiệp vụ phía server',
    demandSalary: 'Junior: 12-20tr, Senior: 35-70tr/tháng',
    characteristics: 'Đòi hỏi tư duy hệ thống, hiểu sâu về DB, caching, message queue',
    requiredSkills: ['nodejs/python/go/java', 'postgresql/mysql', 'mongodb/redis', 'restful api', 'authentication (jwt/oauth)', 'database design', 'docker'],
    bonusSkills: ['graphql', 'grpc', 'microservices architecture', 'kafka/rabbitmq', 'elasticsearch', 'aws/azure/gcp', 'ci/cd pipeline'],
    certifications: ['Oracle Java SE', 'AWS Developer', 'MongoDB Certified']
  },
  {
    id: 'fullstack-developer',
    name: 'Full-Stack Developer',
    rating: '9/10',
    category: 'Development',
    description: 'Phát triển cả Frontend và Backend, end-to-end development',
    demandSalary: 'Junior: 15-25tr, Senior: 40-80tr/tháng',
    characteristics: 'Cần cân bằng giữa depth và breadth, startup rất ưa chuộng',
    requiredSkills: ['react/vue', 'nodejs/spring/django', 'typescript', 'sql & nosql', 'rest/graphql', 'docker', 'git'],
    bonusSkills: ['next.js', 'system design', 'cloud architecture (aws)', 'ci/cd', 'redis caching', 'microservices basics', 'automated testing'],
    certifications: ['Meta Full-Stack', 'AWS Developer', 'MongoDB Certified']
  },
  {
    id: 'mobile-developer',
    name: 'Mobile Developer (iOS/Android)',
    rating: '8.5/10',
    category: 'Development',
    description: 'Phát triển ứng dụng di động native và cross-platform',
    demandSalary: 'Junior: 12-22tr, Senior: 35-65tr/tháng',
    characteristics: 'Cross-platform (Flutter, React Native) đang lên ngôi, native vẫn quan trọng cho performance',
    requiredSkills: ['kotlin', 'swift', 'dart', 'flutter', 'react native', 'mobile ui/ux', 'rest api', 'sqlite', 'git'],
    bonusSkills: ['jetpack compose', 'swiftui', 'firebase', 'push notifications', 'app store optimization', 'ci/cd mobile'],
    certifications: ['Google Associate Android', 'Apple Developer', 'Meta React Native']
  },
  {
    id: 'game-developer',
    name: 'Game Developer / Lập trình Game',
    rating: '7.5/10',
    category: 'Development',
    description: 'Phát triển game 2D/3D, game engine, gameplay programming',
    demandSalary: 'Junior: 10-18tr, Senior: 30-60tr/tháng',
    characteristics: 'Đam mê cao, cạnh tranh khốc liệt, cần hiểu sâu về đồ họa và vật lý',
    requiredSkills: ['c++', 'c#', 'unity', 'unreal engine', 'game physics', 'game design', '3d math', 'shader programming', 'git'],
    bonusSkills: ['godot', 'vulkan', 'opengl', 'multiplayer networking', 'procedural generation', 'ai pathfinding'],
    certifications: ['Unity Certified Developer', 'Unreal Certified', 'Epic Games Certification']
  },
  {
    id: 'embedded-iot',
    name: 'Embedded / IoT Engineer',
    rating: '8/10',
    category: 'Hardware & Embedded',
    description: 'Lập trình vi điều khiển, hệ thống nhúng, Internet of Things',
    demandSalary: 'Junior: 10-18tr, Senior: 30-55tr/tháng',
    characteristics: 'Đòi hỏi kiến thức phần cứng + phần mềm, thị trường IoT đang bùng nổ',
    requiredSkills: ['c', 'c++', 'embedded c', 'rtos', 'arm', 'arduino', 'raspberry pi', 'uart', 'spi', 'i2c', 'mqtt', 'iot protocols'],
    bonusSkills: ['fpga', 'vhdl', 'pcb design', 'edge computing', 'aws iot', 'bluetooth le', 'zigbee'],
    certifications: ['ARM Certified', 'AWS IoT', 'Cisco IoT']
  },
  {
    id: 'qa-tester',
    name: 'QA / Software Tester',
    rating: '7.5/10',
    category: 'Quality & Testing',
    description: 'Kiểm thử phần mềm, đảm bảo chất lượng sản phẩm',
    demandSalary: 'Junior: 8-15tr, Senior: 25-45tr/tháng',
    characteristics: 'Automation Testing đang thay thế Manual, cần chuyển hướng sớm',
    requiredSkills: ['manual testing', 'test cases', 'bug tracking', 'selenium', 'jira', 'api testing', 'postman', 'sql', 'agile testing'],
    bonusSkills: ['cypress', 'playwright', 'jmeter', 'load testing', 'security testing', 'ci/cd integration', 'appium'],
    certifications: ['ISTQB Foundation', 'ISTQB Advanced', 'Certified Agile Tester']
  },
  {
    id: 'database-admin',
    name: 'Database Administrator (DBA)',
    rating: '8/10',
    category: 'Infrastructure',
    description: 'Quản trị, tối ưu và bảo mật cơ sở dữ liệu',
    demandSalary: 'Junior: 12-20tr, Senior: 35-60tr/tháng',
    characteristics: 'Vai trò then chốt trong enterprise, đòi hỏi kinh nghiệm thực tế cao',
    requiredSkills: ['sql', 'mysql', 'postgresql', 'oracle', 'sql server', 'database tuning', 'backup recovery', 'replication', 'indexing', 'stored procedures'],
    bonusSkills: ['mongodb', 'redis', 'cassandra', 'database migration', 'partitioning', 'sharding', 'cloud databases'],
    certifications: ['Oracle DBA', 'MySQL DBA', 'Microsoft SQL Certified', 'MongoDB DBA']
  },
  {
    id: 'network-engineer',
    name: 'Network Engineer / Kỹ sư Mạng',
    rating: '8/10',
    category: 'Infrastructure',
    description: 'Thiết kế, triển khai và quản lý hạ tầng mạng doanh nghiệp',
    demandSalary: 'Junior: 10-18tr, Senior: 30-55tr/tháng',
    characteristics: 'Nền tảng vững chắc cho chuyển hướng Cloud/Security',
    requiredSkills: ['tcp/ip', 'routing', 'switching', 'vlan', 'vpn', 'firewall', 'dns', 'dhcp', 'cisco', 'network monitoring'],
    bonusSkills: ['sdn', 'sd-wan', 'network automation', 'python networking', 'load balancing', 'wireless'],
    certifications: ['CCNA', 'CCNP', 'CompTIA Network+', 'Juniper JNCIA']
  },
  {
    id: 'system-admin',
    name: 'System Administrator / Quản trị Hệ thống',
    rating: '7.5/10',
    category: 'Infrastructure',
    description: 'Quản lý server, hệ điều hành, dịch vụ hạ tầng CNTT',
    demandSalary: 'Junior: 10-16tr, Senior: 25-45tr/tháng',
    characteristics: 'Đang chuyển dịch sang Cloud Admin/DevOps, cần upskill liên tục',
    requiredSkills: ['linux', 'windows server', 'active directory', 'vmware', 'backup', 'scripting', 'bash', 'powershell', 'monitoring', 'troubleshooting'],
    bonusSkills: ['ansible', 'terraform', 'aws', 'azure', 'containerization', 'automation'],
    certifications: ['RHCSA', 'RHCE', 'CompTIA Server+', 'Microsoft MCSA', 'VMware VCP']
  },
  {
    id: 'business-analyst',
    name: 'Business Analyst (IT/BA)',
    rating: '8/10',
    category: 'Management & Analysis',
    description: 'Phân tích yêu cầu, cầu nối giữa business và development team',
    demandSalary: 'Junior: 12-20tr, Senior: 30-55tr/tháng',
    characteristics: 'Cần hiểu cả nghiệp vụ lẫn kỹ thuật, kỹ năng giao tiếp xuất sắc',
    requiredSkills: ['requirements analysis', 'uml', 'user stories', 'sql', 'jira', 'confluence', 'wireframing', 'data analysis', 'process modeling', 'agile'],
    bonusSkills: ['power bi', 'tableau', 'api understanding', 'product management', 'stakeholder management'],
    certifications: ['CBAP', 'PMI-PBA', 'Scrum Product Owner', 'IIBA Certification']
  },
  {
    id: 'project-manager',
    name: 'IT Project Manager / Scrum Master',
    rating: '8.5/10',
    category: 'Management & Analysis',
    description: 'Quản lý dự án phần mềm, điều phối team, đảm bảo tiến độ',
    demandSalary: 'PM: 20-50tr, Senior PM: 40-80tr/tháng',
    characteristics: 'Leadership + Technical understanding, Agile/Scrum là bắt buộc',
    requiredSkills: ['agile', 'scrum', 'project planning', 'risk management', 'jira', 'confluence', 'stakeholder management', 'budget management', 'team leadership'],
    bonusSkills: ['safe', 'kanban', 'devops understanding', 'technical architecture', 'okr', 'lean'],
    certifications: ['PMP', 'CSM', 'PSM', 'SAFe Agilist', 'PRINCE2']
  },
  {
    id: 'ui-ux-designer',
    name: 'UI/UX Designer',
    rating: '8/10',
    category: 'Design',
    description: 'Thiết kế trải nghiệm và giao diện người dùng cho sản phẩm số',
    demandSalary: 'Junior: 10-18tr, Senior: 30-55tr/tháng',
    characteristics: 'Cần kết hợp tư duy sáng tạo với nghiên cứu người dùng và data-driven design',
    requiredSkills: ['figma', 'adobe xd', 'user research', 'wireframing', 'prototyping', 'design system', 'typography', 'color theory', 'usability testing', 'responsive design'],
    bonusSkills: ['motion design', 'design tokens', 'accessibility', 'a/b testing', 'html/css', 'interaction design'],
    certifications: ['Google UX Design', 'Nielsen Norman UX', 'Interaction Design Foundation']
  },
  {
    id: 'blockchain-developer',
    name: 'Blockchain / Web3 Developer',
    rating: '7.5/10',
    category: 'Emerging Tech',
    description: 'Smart contracts, DApps, DeFi, NFT platforms',
    demandSalary: 'Junior: 15-25tr, Senior: 40-100tr/tháng (biến động cao)',
    characteristics: 'Thị trường biến động, nhưng công nghệ nền tảng vẫn phát triển mạnh',
    requiredSkills: ['solidity', 'ethereum', 'smart contracts', 'web3.js', 'hardhat', 'cryptography', 'dapps', 'javascript', 'git'],
    bonusSkills: ['rust', 'solana', 'defi', 'nft', 'layer2', 'cross-chain', 'tokenomics', 'ipfs'],
    certifications: ['Certified Blockchain Developer', 'Ethereum Developer', 'Hyperledger']
  },
  {
    id: 'erp-consultant',
    name: 'ERP Consultant / SAP Specialist',
    rating: '8/10',
    category: 'Enterprise',
    description: 'Triển khai, tùy chỉnh hệ thống quản trị doanh nghiệp (SAP, Oracle ERP)',
    demandSalary: 'Junior: 15-25tr, Senior: 40-80tr/tháng',
    characteristics: 'Ổn định, lương cao, đặc biệt trong các tập đoàn lớn và FDI',
    requiredSkills: ['sap', 'erp', 'abap', 'business process', 'sql', 'data migration', 'system integration', 'functional consulting'],
    bonusSkills: ['sap s/4hana', 'sap fiori', 'oracle erp', 'salesforce', 'dynamics 365'],
    certifications: ['SAP Certified', 'Oracle ERP Certified', 'Salesforce Certified']
  },
  {
    id: 'technical-support',
    name: 'IT Support / Help Desk / Technical Support',
    rating: '6.5/10',
    category: 'Support',
    description: 'Hỗ trợ kỹ thuật, xử lý sự cố CNTT cho doanh nghiệp và người dùng',
    demandSalary: 'Junior: 7-12tr, Senior: 18-30tr/tháng',
    characteristics: 'Điểm khởi đầu tốt cho career path IT, cần upskill để thăng tiến',
    requiredSkills: ['troubleshooting', 'windows', 'networking basics', 'hardware', 'ticketing systems', 'customer service', 'active directory', 'remote support'],
    bonusSkills: ['linux', 'scripting', 'cloud basics', 'itil', 'virtualization', 'powershell'],
    certifications: ['CompTIA A+', 'ITIL Foundation', 'Microsoft 365 Certified', 'Google IT Support']
  },
  {
    id: 'product-manager',
    name: 'Product Manager (Tech)',
    rating: '9/10',
    category: 'Management & Analysis',
    description: 'Định hướng sản phẩm công nghệ, chiến lược phát triển, roadmap',
    demandSalary: 'Junior: 18-30tr, Senior: 45-90tr/tháng',
    characteristics: 'Kết hợp business + tech + UX, vai trò then chốt tại startup và product company',
    requiredSkills: ['product strategy', 'roadmap planning', 'user research', 'data analysis', 'a/b testing', 'agile', 'jira', 'sql', 'stakeholder management'],
    bonusSkills: ['growth hacking', 'pricing strategy', 'api understanding', 'analytics tools', 'figma'],
    certifications: ['Product Management Certificate', 'Scrum Product Owner', 'Google PM Certificate']
  },
  {
    id: 'solutions-architect',
    name: 'Solutions Architect / Kiến trúc sư Giải pháp',
    rating: '9.5/10',
    category: 'Architecture',
    description: 'Thiết kế kiến trúc hệ thống toàn diện, lựa chọn công nghệ phù hợp',
    demandSalary: 'Senior: 50-120tr/tháng',
    characteristics: 'Đỉnh cao career path của SE, đòi hỏi kinh nghiệm đa dạng 7+ năm',
    requiredSkills: ['system design', 'microservices', 'cloud architecture', 'aws', 'azure', 'api design', 'database design', 'security architecture', 'scalability', 'high availability'],
    bonusSkills: ['enterprise integration', 'cost optimization', 'multi-cloud', 'serverless', 'event-driven architecture'],
    certifications: ['AWS Solutions Architect Professional', 'Azure Solutions Architect', 'TOGAF']
  },
  {
    id: 'data-analyst',
    name: 'Data Analyst / Phân tích Dữ liệu',
    rating: '8.5/10',
    category: 'AI & Data',
    description: 'Phân tích dữ liệu kinh doanh, tạo dashboard, báo cáo insight',
    demandSalary: 'Junior: 10-18tr, Senior: 25-50tr/tháng',
    characteristics: 'Dễ tiếp cận hơn Data Engineer/Scientist, nhu cầu rất cao ở mọi ngành',
    requiredSkills: ['sql', 'excel', 'python', 'power bi', 'tableau', 'statistics', 'data visualization', 'etl basics', 'reporting'],
    bonusSkills: ['r', 'google analytics', 'looker', 'dbt', 'a/b testing', 'machine learning basics'],
    certifications: ['Google Data Analytics', 'Microsoft Power BI', 'Tableau Desktop Specialist']
  },
  {
    id: 'robotics-engineer',
    name: 'Robotics Engineer / Kỹ sư Robot',
    rating: '8/10',
    category: 'Hardware & Embedded',
    description: 'Thiết kế, lập trình và điều khiển robot tự động',
    demandSalary: 'Junior: 12-20tr, Senior: 35-65tr/tháng',
    characteristics: 'Kết hợp cơ khí + điện tử + AI, thị trường đang mở rộng nhanh',
    requiredSkills: ['python', 'c++', 'ros', 'computer vision', 'sensor fusion', 'control systems', 'kinematics', 'embedded systems', 'linux'],
    bonusSkills: ['slam', 'reinforcement learning', 'simulation', 'gazebo', 'plc', 'industrial automation'],
    certifications: ['ROS Certified', 'ABB Robotics', 'Universal Robots']
  },
  {
    id: 'gis-specialist',
    name: 'GIS Developer / Chuyên viên Hệ thống Thông tin Địa lý',
    rating: '7.5/10',
    category: 'Specialized',
    description: 'Xây dựng ứng dụng bản đồ, phân tích dữ liệu không gian',
    demandSalary: 'Junior: 10-16tr, Senior: 25-45tr/tháng',
    characteristics: 'Niche nhưng ổn định, ứng dụng rộng trong logistics, smart city',
    requiredSkills: ['gis', 'arcgis', 'qgis', 'python', 'sql', 'spatial databases', 'leaflet', 'mapbox', 'remote sensing'],
    bonusSkills: ['postgis', 'google earth engine', 'lidar', 'web mapping', 'geodatabase'],
    certifications: ['Esri Technical', 'GIS Professional (GISP)']
  }
];

export const JOB_CATEGORIES = [
  { id: 'all', label: 'Tất cả ngành' },
  { id: 'Development', label: 'Phát triển Phần mềm' },
  { id: 'AI & Data', label: 'AI & Dữ liệu' },
  { id: 'Infrastructure', label: 'Hạ tầng & Cloud' },
  { id: 'Security', label: 'An ninh mạng' },
  { id: 'Quality & Testing', label: 'Kiểm thử' },
  { id: 'Management & Analysis', label: 'Quản lý & Phân tích' },
  { id: 'Design', label: 'Thiết kế' },
  { id: 'Hardware & Embedded', label: 'Phần cứng & Nhúng' },
  { id: 'Emerging Tech', label: 'Công nghệ mới nổi' },
  { id: 'Enterprise', label: 'Hệ thống Doanh nghiệp' },
  { id: 'Support', label: 'Hỗ trợ Kỹ thuật' },
  { id: 'Architecture', label: 'Kiến trúc Hệ thống' },
  { id: 'Specialized', label: 'Chuyên ngành' },
];

export default IT_JOB_POSITIONS;
